### ISSUE TITLE
question

### ISSUE THREAD

**Issue by QuintenQVD0** [DoJoMan18/fs22_ptero#17]
Did you get it to work? like 

Were you able to setup the server over the web panel and join withoud running the wings in host mode?

**Comment by QuintenQVD0** [comment]
looks like your not active. I just try it myself

**Comment by DoJoMan18** [comment]
Hi @QuintenQVD0 ,

I did get the web interface working with wine. But for some reason the game (server) wouldnt start. Please let me know if you get it working!

**Comment by QuintenQVD0** [comment]
Ik zie dat je Nederlands spreekt, ik zal het vrijdag avond proberen

**Comment by DoJoMan18** [comment]
Helemaal goed, ik ben erg benieuwd. Zover ik kwam zat hij vooral met wine te kloten om de game op te starten. Ergens iets met de graphics ofzo.

 Zover ik het namelijk begrijp is dat de server gewoon een game is, die automatisch een lokale game openzet naar buiten. 

Dat FS22 sws al geen linux installatie voor een server heeft is eigenlijk al gewoon shit, maar goed!

**Comment by QuintenQVD0** [comment]
just to let you know. I got the dashboard to start with proton not regular wine. but the server gave a error and the log files where kept empty so yea no luck
